// ==========================================================
// SENTINEL AI
// File: activity_screen.dart
//
// Description:
// Displays the complete scan history generated by
// the Scan Engine.
//
// Author: Ab Junior
// ==========================================================

import 'package:flutter/material.dart';

import '../../services/latest_scan_service.dart';
import '../scan/scan_engine.dart';

class ActivityScreen extends StatelessWidget {
  const ActivityScreen({super.key});

  @override
  Widget build(BuildContext context) {

    // Retrieve all completed scans.
    final List<ScanResult> history =
        LatestScanService.getHistory();

    return Scaffold(
      appBar: AppBar(
        title: const Text("Recent Scans"),
        backgroundColor: const Color(0xFF0B3D91),
        foregroundColor: Colors.white,
      ),

      body: history.isEmpty

          // ==================================================
          // EMPTY STATE
          // ==================================================
          ? const Center(
              child: Text(
                "📊\n\nNo scan history yet.",
                textAlign: TextAlign.center,
                style: TextStyle(
                  fontSize: 22,
                  fontWeight: FontWeight.bold,
                ),
              ),
            )

          // ==================================================
          // SCAN HISTORY
          // ==================================================
          : ListView.builder(

              padding: const EdgeInsets.all(16),

              itemCount: history.length,

              itemBuilder: (context, index) {

                final scan = history[index];

                Color statusColor;

                IconData statusIcon;

                if (scan.protectionScore >= 90) {
                  statusColor = Colors.green;
                  statusIcon = Icons.check_circle;
                } else if (scan.protectionScore >= 70) {
                  statusColor = Colors.orange;
                  statusIcon = Icons.warning;
                } else {
                  statusColor = Colors.red;
                  statusIcon = Icons.cancel;
                }

                final time =
                    "${scan.scanTime.hour.toString().padLeft(2, '0')}:"
                    "${scan.scanTime.minute.toString().padLeft(2, '0')}";

                return Card(
                  margin: const EdgeInsets.only(bottom: 15),
                  elevation: 4,

                  child: ListTile(

                    leading: Icon(
                      statusIcon,
                      color: statusColor,
                      size: 35,
                    ),

                    title: Text(
                      scan.securityLevel,
                      style: const TextStyle(
                        fontWeight: FontWeight.bold,
                        fontSize: 18,
                      ),
                    ),

                    subtitle: Column(
                      crossAxisAlignment:
                          CrossAxisAlignment.start,
                      children: [

                        const SizedBox(height: 6),

                        Text(
                          "Protection Score: ${scan.protectionScore}%",
                        ),

                        Text(
                          time,
                        ),
                      ],
                    ),
                  ),
                );
              },
            ),
    );
  }
}